global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['app_instance_1:8000', 'app_instance_2:8001']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['datahub:5432']
